### ISSUE TITLE
Moveing between monitors having different scaling causes window shift on resize

### ISSUE THREAD

**Issue by ponchofiesta** [vizia/vizia#534]
Having two monitors using different scaling causes issues when moving a window between them. A window resizes its physical size when moving between these monitors. In specific scenarios the window moves itself back to the previous monitor when the window resizes itself.

Here is an example to make this more clear:

- Left monitor has scaling 1.5
- Right monitor has scaling 1.75
- Move the window from right to left

Result:
As soon as the window has passed half to the left monitor, the window resizes itself and gets bigger. x and y position stays the same. The center of the window is now back to right monitor. When moving further to the left, the windows enlarges everytime the center of the window passes the monitors.

Possible solution:
- When moving from higher scaling factor to lower scaling factor the window physical size needs to shrink (actually it gets bigger).
- When resizing the window position needs to adapt to make the window center position stay on the same size. This is what other Windows programs behave (e.g. Windows Explorer and Calculator).

This may or may not be related to #522 But I think this is another problem.

https://github.com/user-attachments/assets/95f611c6-0d28-489a-9b23-adb9fe1464a4

**Comment by geom3trik** [comment]
Sorry for the delay but this should be fixed now.

**Comment by ponchofiesta** [comment]
Thank you. I just tested the current main revision on the timers demo. For me it didn't fix this issue. But now the window content is left aligned.

But the scaling of the content is looking good now. Maybe this fix was intended for #522 ?

**Comment by geom3trik** [comment]
The left alignment a separate issue due to a new layout system. Both issues should be fixed on main now.

**Comment by ponchofiesta** [comment]
Alignment is fixed again but the root issue here does still exist.

**Comment by geom3trik** [comment]
Relevant winit PR: https://github.com/rust-windowing/winit/pull/4119
